import { useEffect, useRef, useState, type ReactNode } from 'react'
import {
  CircleAlertIcon,
  CodeXmlIcon,
  GitForkIcon,
  LayersIcon,
  LinkIcon,
  Loader2Icon,
  PencilIcon,
  StickyNoteIcon,
  Trash2Icon,
  XIcon,
} from 'lucide-react'
import { toast } from 'sonner'

import { api } from '@/api/client'
import type { BriefResource, StackMember, StackView } from '@/api/types'
import { InlineEdit } from '@/components/InlineEdit'
import { Markdown } from '@/components/Markdown'
import { StatusDot } from '@/components/StatusDot'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog'
import { Skeleton } from '@/components/ui/skeleton'
import { useFleet } from '@/hooks/useFleet'
import { useNow } from '@/hooks/useNow'
import { STACK_POLL_MS, useStack } from '@/hooks/useStack'
import { useRenameStack, useStackLabel } from '@/hooks/useStackLabels'
import { openSiblingSpawn } from '@/hooks/useStackUi'
import { briefTime, editorLabel, gitLine } from '@/lib/brief'
import { relTime, shortCwd } from '@/lib/format'
import { findSession, sessionHref, statusLabel, statusMeta } from '@/lib/sessions'
import {
  MAX_STACK_LABEL,
  conflictUpdated,
  memberCountsText,
  memberLive,
  memberSession,
  sortedMembers,
  stackErrorMessage,
  stackLabelChanged,
} from '@/lib/stacks'
import { STATUS_TEXT } from '@/lib/styles'
import { sessionTitle } from '@/lib/title'
import { cn } from '@/lib/utils'

export interface StackSheetProps {
  /** The stack to show; null = closed. */
  target: { host: string; id: string } | null
  onClose: () => void
  /** Open a member session (`#/s/<host>/<id>`). */
  onNavigate: (href: string) => void
  desktop: boolean
}

/**
 * A session stack: label (click to rename — not while the markdown editor is open, whose
 * `label:` line would race it), members (live / closed, status, → the session) and its StackBrief —
 * read (Summary, Resources, Notes) or edited as the whole markdown file (label in the
 * frontmatter; `## Sessions` is regenerated by fleet). Save sends `expectUpdated`: a 409 means
 * it changed elsewhere → toast + reload, the edit stays open. Polls every 15 s while open.
 * Desktop: a large dialog; mobile: full screen (like the file preview).
 */
export function StackSheet({ target, onClose, onNavigate, desktop }: StackSheetProps) {
  const cancelEdit = useRef<(() => void) | null>(null)
  return (
    <Dialog open={!!target} onOpenChange={(o) => (o ? null : onClose())}>
      <DialogContent
        showCloseButton={false}
        onEscapeKeyDown={(e) => {
          if (!cancelEdit.current) return
          e.preventDefault()
          cancelEdit.current()
        }}
        className={cn(
          'flex flex-col gap-0 overflow-hidden p-0 sm:max-w-none',
          desktop
            ? 'h-[min(88vh,56rem)] w-[min(96vw,760px)] max-w-none'
            : 'top-0 left-0 h-app w-full max-w-none translate-x-0 translate-y-0 rounded-none pt-safe pb-safe ring-0',
        )}
      >
        {target ? (
          <StackBody key={`${target.host}/${target.id}`} host={target.host} id={target.id} onClose={onClose} onNavigate={onNavigate} desktop={desktop} cancelEditRef={cancelEdit} />
        ) : null}
      </DialogContent>
    </Dialog>
  )
}

function StackBody({
  host,
  id,
  onClose,
  onNavigate,
  desktop,
  cancelEditRef,
}: {
  host: string
  id: string
  onClose: () => void
  onNavigate: (href: string) => void
  desktop: boolean
  cancelEditRef: React.RefObject<(() => void) | null>
}) {
  const st = useStack(host, id, true, STACK_POLL_MS)
  const s = st.stack
  const now = useNow(15_000)
  const { refresh: refreshFleet } = useFleet()

  // Editing: the whole file; `base` = the `updated` the edit is based on (sent as expectUpdated).
  const [edit, setEdit] = useState<{ draft: string; base: string | null; conflict: boolean } | null>(null)
  const [saving, setSaving] = useState(false)
  const textRef = useRef<HTMLTextAreaElement>(null)
  const editing = edit !== null
  // The label, renamed in place (optimistic, hooks/useStackLabels.ts).
  const [naming, setNaming] = useState(false)
  const { label, saving: renaming } = useStackLabel(host, id, s?.label || id)
  const renameStack = useRenameStack()
  const rename = async (text: string) => {
    if (!stackLabelChanged(text, label)) return
    const next = await renameStack(host, id, text)
    if (!next) return
    // A fresh `updated` for the next Save (its expectUpdated).
    st.apply(next)
    st.refresh()
  }
  useEffect(() => {
    // Esc while the label is edited: the field cancels itself; the dialog must stay open.
    cancelEditRef.current = editing ? () => setEdit(null) : naming ? () => {} : null
    return () => {
      cancelEditRef.current = null
    }
  }, [cancelEditRef, editing, naming])
  useEffect(() => {
    if (editing) textRef.current?.focus()
  }, [editing])

  const save = async () => {
    if (!edit || saving) return
    setSaving(true)
    try {
      const next = await api.saveStack(host, id, edit.draft, edit.base)
      st.apply(next)
      setEdit(null)
      toast.success('StackBrief saved', { duration: 1800 })
      // A new label shows on rows / columns with the next fleet poll.
      refreshFleet()
    } catch (err) {
      const updated = conflictUpdated(err)
      if (updated != null || (err as { status?: number })?.status === 409) {
        toast.error('StackBrief changed elsewhere', { description: 'Reloaded — your edit is still open; Save again to overwrite it.' })
        setEdit((e) => (e ? { ...e, base: updated, conflict: true } : e))
        st.refresh()
      } else toast.error('Could not save the StackBrief', { description: stackErrorMessage(err) })
    } finally {
      setSaving(false)
    }
  }

  // Delete: two clicks (the first arms for 5 s), like Close session.
  const [armed, setArmed] = useState(false)
  const [deleting, setDeleting] = useState(false)
  const armTimer = useRef<ReturnType<typeof setTimeout>>(undefined)
  useEffect(() => () => clearTimeout(armTimer.current), [])
  const remove = async () => {
    if (deleting) return
    if (!armed) {
      setArmed(true)
      clearTimeout(armTimer.current)
      armTimer.current = setTimeout(() => setArmed(false), 5000)
      return
    }
    clearTimeout(armTimer.current)
    setDeleting(true)
    try {
      await api.deleteStack(host, id)
      toast.success(`Deleted stack ${label || id}`, { description: 'The sessions keep running.' })
      onClose()
      refreshFleet()
    } catch (err) {
      toast.error('Could not delete the stack', { description: stackErrorMessage(err) })
      setDeleting(false)
      setArmed(false)
    }
  }

  const spawnSibling = () =>
    openSiblingSpawn({ host, stackId: id, cwd: s?.absCwd ?? s?.cwd ?? null, label: label || null, creates: false })

  const updated = briefTime(s?.updated)
  const edited = briefTime(s?.editedAt)
  const editorText = editorLabel(null, s?.editorUrl)
  const meta = [host, s?.cwd ? shortCwd(s.cwd, 60) : null, s ? memberCountsText(s) : null, updated ? `updated ${relTime(updated, now)} ago${edited ? ' · edited' : ''}` : null]
    .filter(Boolean)
    .join(' · ')

  const openMember = (m: StackMember) => {
    onClose()
    onNavigate(sessionHref(memberSession(m, host)))
  }

  let body: ReactNode
  if (!s) {
    body = st.missing ? (
      <Notice>This host’s fleet web server predates session stacks — update and restart it.</Notice>
    ) : st.error ? (
      <Notice>{st.error}</Notice>
    ) : (
      <div className="space-y-2 p-4" aria-hidden>
        <Skeleton className="h-4 w-2/3" />
        <Skeleton className="h-4 w-1/2" />
        <Skeleton className="mt-6 h-4 w-full" />
        <Skeleton className="h-4 w-4/5" />
      </div>
    )
  } else if (edit) {
    body = (
      <div className="flex min-h-0 flex-1 flex-col gap-2 p-4">
        {edit.conflict ? (
          <p className="flex items-start gap-2 rounded-lg border border-status-waiting/40 bg-status-waiting/10 px-3 py-2 text-xs">
            <CircleAlertIcon className="mt-px size-3.5 shrink-0 text-status-waiting" />
            <span>The StackBrief changed elsewhere while you edited. Save again to overwrite it, or Cancel to see the new version.</span>
          </p>
        ) : null}
        <textarea
          ref={textRef}
          value={edit.draft}
          onChange={(e) => setEdit({ ...edit, draft: e.target.value })}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
              e.preventDefault()
              void save()
            }
          }}
          aria-label="StackBrief markdown"
          spellCheck={false}
          className={cn(
            'min-h-48 w-full flex-1 resize-none rounded-lg border border-input bg-card px-3 py-2 font-mono text-[0.8125rem] leading-relaxed outline-none',
            'focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50',
          )}
        />
        <div className="flex items-center gap-2">
          <span className="min-w-0 flex-1 truncate text-xs text-dimmer">
            {desktop ? '⌘/Ctrl+Enter saves · Esc cancels · ' : ''}`label:` renames · Sessions is kept by fleet
          </span>
          <Button variant="ghost" className="h-9 px-3" onClick={() => setEdit(null)} disabled={saving}>
            Cancel
          </Button>
          <Button className="h-9 px-4" onClick={() => void save()} disabled={saving}>
            {saving ? <Loader2Icon className="animate-spin" /> : null}
            Save
          </Button>
        </div>
      </div>
    )
  } else {
    body = (
      <div className="no-scrollbar min-h-0 flex-1 space-y-5 overflow-y-auto p-4">
        <Members stack={s} onOpen={openMember} now={now} />
        <Part
          title="StackBrief"
          aside={
            <Button
              variant="ghost"
              size="icon"
              aria-label="Edit StackBrief"
              title="Edit"
              onClick={() => setEdit({ draft: s.markdown, base: s.updated, conflict: false })}
              className="-my-1.5 size-8 rounded-lg"
            >
              <PencilIcon />
            </Button>
          }
        >
          <div className="space-y-4">
            <Sub title="Summary">
              {s.parsed?.summary ? <Markdown text={s.parsed.summary} className="text-sm leading-relaxed" /> : <p className="text-sm text-dimmer">No summary yet.</p>}
            </Sub>
            {s.parsed?.resources?.length ? (
              <Sub title="Resources">
                <ul className="space-y-1">
                  {s.parsed.resources.map((r, i) => (
                    <ResourceRow key={`${r.text}-${i}`} r={r} />
                  ))}
                </ul>
              </Sub>
            ) : null}
            {s.parsed?.notes?.trim() ? (
              <Sub title="Notes">
                <Markdown text={s.parsed.notes} className="text-sm leading-relaxed" />
              </Sub>
            ) : null}
            <p className="text-xs break-all text-dimmer">
              <span className="font-mono select-all">{s.path}</span>
            </p>
          </div>
        </Part>
      </div>
    )
  }

  return (
    <>
      <header className="shrink-0 border-b px-safe">
        <div className="flex items-start gap-2 px-4 py-3">
          <LayersIcon className="mt-0.5 size-4 shrink-0 text-primary" />
          <div className="min-w-0 flex-1">
            <DialogTitle className="flex min-w-0 items-center gap-1 text-[0.9375rem] leading-tight font-semibold">
              {s ? (
                <InlineEdit
                  value={label}
                  editing={naming && !editing}
                  onEdit={editing || renaming ? undefined : () => setNaming(true)}
                  onCommit={(text) => {
                    setNaming(false)
                    void rename(text)
                  }}
                  onCancel={() => setNaming(false)}
                  className={cn(renaming && 'opacity-70')}
                  label="Stack name"
                  hint="Rename stack"
                  maxLength={MAX_STACK_LABEL}
                  tapToEdit
                />
              ) : (
                <span className="truncate">Session stack</span>
              )}
              {renaming ? <Loader2Icon aria-label="Saving" className="size-3 shrink-0 animate-spin text-dimmer" /> : null}
            </DialogTitle>
            <DialogDescription className="mt-0.5 truncate text-xs text-muted-foreground tabular-nums" title={s?.path}>
              {meta || host}
            </DialogDescription>
          </div>
          <Button variant="ghost" size="icon" aria-label="Close" onClick={onClose} className={cn('-mt-1 -mr-2 shrink-0 rounded-xl', desktop ? '' : 'size-11')}>
            <XIcon className="size-5" />
          </Button>
        </div>
      </header>
      {body}
      {s && !edit ? (
        <footer className="shrink-0 border-t px-safe">
          <div className="flex flex-wrap items-center gap-2 px-4 py-3">
          <Button className="h-10 rounded-xl px-4" onClick={spawnSibling}>
            <GitForkIcon />
            Spawn sibling
          </Button>
          {editorText && s.editorUrl ? (
            <Button asChild variant="outline" className="h-10 rounded-xl px-3 pointer-coarse:hidden">
              <a href={s.editorUrl} title={s.editorUrl}>
                <CodeXmlIcon />
                {editorText}
              </a>
            </Button>
          ) : null}
          <Button
            variant="destructive"
            className={cn('ml-auto h-10 rounded-xl px-3', armed && 'bg-destructive text-white hover:bg-destructive/90 dark:bg-destructive dark:hover:bg-destructive/90')}
            disabled={deleting}
            onClick={() => void remove()}
          >
            {deleting ? <Loader2Icon className="animate-spin" /> : <Trash2Icon />}
            {deleting ? 'Deleting…' : armed ? (desktop ? 'Click again to delete' : 'Tap again to delete') : 'Delete stack…'}
          </Button>
          </div>
        </footer>
      ) : null}
    </>
  )
}

function Members({ stack, onOpen, now }: { stack: StackView; onOpen: (m: StackMember) => void; now: number }) {
  const { fleet } = useFleet()
  const members = sortedMembers(stack.members)
  return (
    <Part title="Sessions" aside={<span className="tabular-nums">{memberCountsText(stack)}</span>}>
      {members.length ? (
        <ul className="-mx-2 space-y-0.5">
          {members.map((m) => {
            const live = memberLive(m)
            const ref = memberSession(m, stack.host)
            const session = findSession(fleet, ref.host, ref.session_id)
            const title = session ? sessionTitle(session) : m.name || m.session.slice(0, 8)
            const status = session?.status ?? m.status ?? null
            const closed = briefTime(m.closed)
            return (
              <li key={`${m.host}/${m.session}`}>
                <button
                  type="button"
                  onClick={() => onOpen(m)}
                  className="flex min-h-11 w-full items-center gap-2.5 rounded-lg px-2 text-left outline-none hover:bg-muted/60 focus-visible:ring-3 focus-visible:ring-ring/50 active:bg-muted"
                >
                  {live ? <StatusDot status={status} className="size-2" /> : <span aria-label="closed" className="inline-block size-2 shrink-0 rounded-full border border-dimmer" />}
                  <span className={cn('min-w-0 flex-1 truncate text-sm', !live && 'text-muted-foreground')}>{title}</span>
                  <span className={cn('shrink-0 text-xs', live ? STATUS_TEXT[statusMeta(status).key] : 'text-dimmer')}>
                    {live ? (session ? statusLabel(session) : statusMeta(status).label) : m.dormant ? 'dormant' : closed ? `closed ${relTime(closed, now)} ago` : 'closed'}
                  </span>
                </button>
              </li>
            )
          })}
        </ul>
      ) : (
        <p className="text-sm text-dimmer">No sessions in this stack.</p>
      )}
    </Part>
  )
}

function Part({ title, aside, children }: { title: string; aside?: ReactNode; children: ReactNode }) {
  return (
    <section>
      <h3 className="flex items-center justify-between gap-2 pb-1.5 text-[0.6875rem] font-semibold tracking-wider text-dimmer uppercase">
        {title}
        {aside ? <span className="text-xs font-medium tracking-normal normal-case">{aside}</span> : null}
      </h3>
      {children}
    </section>
  )
}

function Sub({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section>
      <h4 className="pb-1 text-xs font-semibold text-muted-foreground">{title}</h4>
      {children}
    </section>
  )
}

function Notice({ children }: { children: ReactNode }) {
  return (
    <div className="p-4">
      <p className="flex items-start gap-2 rounded-lg border border-destructive/40 bg-destructive/10 px-3 py-2 text-xs text-destructive">
        <CircleAlertIcon className="mt-px size-3.5 shrink-0" />
        <span className="break-words">{children}</span>
      </p>
    </div>
  )
}

const rowClass = 'flex min-w-0 items-start gap-2 rounded-md py-1 text-sm'

/** A `## Resources` bullet: URLs open a new tab, everything else is text (no file preview — a stack has no session scope). */
function ResourceRow({ r }: { r: BriefResource }) {
  const icon = r.url ? <LinkIcon className="mt-0.5 size-4 shrink-0 text-dimmer" /> : <StickyNoteIcon className="mt-0.5 size-4 shrink-0 text-dimmer" />
  if (r.url) {
    return (
      <li className={rowClass}>
        {icon}
        <span className="min-w-0">
          {r.kind ? <span className="pr-1 text-xs text-dimmer">{r.kind}</span> : null}
          <a
            href={r.url}
            target="_blank"
            rel="noopener noreferrer"
            title={r.url}
            className="break-words text-primary underline decoration-primary/40 underline-offset-2 [overflow-wrap:anywhere] active:opacity-70"
          >
            {r.label || r.url}
          </a>
        </span>
      </li>
    )
  }
  if (r.kind == null) {
    return (
      <li className={rowClass}>
        {icon}
        <Markdown text={r.text} className="min-w-0 flex-1 text-sm" />
      </li>
    )
  }
  const text = r.kind === 'Git' ? [gitLine(r).branch ?? 'detached', gitLine(r).where].filter(Boolean).join(' · ') : (r.path ?? r.label ?? r.text)
  return (
    <li className={rowClass}>
      {icon}
      <span className="min-w-0">
        <span className="pr-1 text-xs text-dimmer">{r.kind}</span>
        <span className="font-mono text-[0.8125rem] break-all text-muted-foreground select-all">{text}</span>
      </span>
    </li>
  )
}

